merquemos/api/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import (
    password_reset, password_reset_done,
    password_reset_confirm, password_reset_complete
)
from allauth.account.views import ConfirmEmailView

from users.views import UserDetailsView

urlpatterns = [
    url(r'^docs/', include('rest_framework_docs.urls')),
    url(r'^auth/user/$', UserDetailsView.as_view()),
    url(r'^auth/', include('rest_auth.urls')),
    url(r'^manager/', include('manager.urls')),
    url(r'^stock/', include('stock.urls')),
    url(r'^sales/', include('sales.urls', namespace='sales')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^account-confirm-email/(?P<key>[-:\w]+)/$', ConfirmEmailView.as_view(), name='account_confirm_email'),
    url(
        regex=r'^contrib/password_reset/$',
        view=password_reset,
        name='password_reset'
    ),
    url(
        regex=r'^contrib/password_reset/done/$',
        view=password_reset_done,
        name='password_reset_done'
    ),
    url(
        regex=r'^contrib/reset/(?P<uidb64>[0-9A-Za-z_\-]+)'
              r'/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        view=password_reset_confirm,
        name='password_reset_confirm'
    ),
    url(
        regex=r'^contrib/reset/done/$',
        view=password_reset_complete,
        name='password_reset_complete'
    ),
]

merquemos/merquemos/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from reports.views import ReportView 

urlpatterns = [
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    url(r'^admin/', admin.site.urls),
    url(r'^admin/reports/$', ReportView.as_view(), name="admin-reports"),
    url(r'^', include('webclient.urls', namespace='webclient')),
    url(r'^auth/', include('rest_auth.urls')),
    url(r'^reports/', include('reports.urls', namespace='reports')),
    url(r'^auth/registration/', include('rest_auth.registration.urls')),
    url(r'^api/', include('api.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'webclient.views.custom_404'

admin.site.site_header = 'Administrador Mequemos'
admin.site.site_title = 'Administrador Mequemos'

merquemos/reports/urls.py
from django.conf.urls import url, include

from . import views


app_name = 'reports'
urlpatterns = [
    # url(r'^', views.ReportView.as_view(), name="reports"),
    url(r'^products/', views.RegisteredProducts.as_view(), name='products'),
    url(r'^services/', views.NumberServices.as_view(), name='services'),
    url(r'^rating/', views.Rating.as_view(), name='rating'),
    url(r'^sales/', views.Sales.as_view(), name='sales'),
    url(r'^requests/', views.Requests.as_view(), name='requests'),
    
]

merquemos/sales/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import (
    CurrentOrderDetail, ItemCreate, OrderList,
    CurrentOrderItems, ItemDetail, OrderDetail, checkout,
    RatingCreate, order_cancellation, OrderItems
)

urlpatterns = [
    url(r'^current-order/$', CurrentOrderDetail.as_view(), name="current-order"),
    url(r'^current-order/items/$', CurrentOrderItems.as_view(), name="current-order-items"),
    url(r'^orders/$', OrderList.as_view(), name="order-list"),
    url(r'^order/(?P<pk>[0-9]+)/$', OrderDetail.as_view(), name="order-detail"),
    url(r'^order/(?P<pk>[0-9]+)/items/$', OrderItems.as_view(), name="order-items"),
    url(r'^item/$', ItemCreate.as_view(), name="item-create"),
    url(r'^item/(?P<pk>[0-9]+)/$', ItemDetail.as_view(), name="item-detail"),
    url(r'^checkout/$', checkout, name="checkout"),
    url(r'^cancellation/$', order_cancellation, name="cancellation"),
    url(r'^rating/$', RatingCreate.as_view(), name="rating-create"),
]

merquemos/reports/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

merquemos/reports/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import datetime
import xlwt

from django.db.models import Avg, Count, Min, Sum, F
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic import TemplateView

from django_xhtml2pdf.utils import generate_pdf

from manager.models import State, City
from sales.models import Order
from stock.models import Product, Store
# from users.models import User


class ReportView(TemplateView):
    template_name = 'reports/report_list.html'

    def get_context_data(self, **kwargs):
        context = super(ReportView, self).get_context_data(**kwargs)
        context['stores'] = Store.objects.all()
        states = State.objects.all()
        context['states'] = State.objects.all()
        return context
    
    def generate_pdf_report(self, request, report, start_date, end_date):
        if report == "register_products":
            products = Product.objects.filter(date_added__gte=start_date, date_added__lte=end_date)
            context = {
                'headers': (
                    'Nombre',
                    'Descripción',
                    'Precio',
                ),
                'products': products,
                'start_date': start_date,
                'end_date': end_date
            }
            report_template_name = 'reports/products_registered.html'
        elif report == "number_services":
            store = Store.objects.get(pk=request.POST['store'])
            orders = Order.objects.filter(
                related_items__product__store=store, 
                status='DE', 
                date_added__gte=start_date, 
                date_added__lte=end_date
            )
            orders_count = orders.count()
            total_no_tax = 0
            total_tax = 0
            total_with_tax = 0
            if orders_count > 0:
                for order in orders:
                    total_no_tax += order.get_total_no_tax()
                    total_tax += order.get_total_tax()
                    total_with_tax += order.get_total_with_tax()

            context = {
                'store': store,
                'count': orders_count,
                'start_date': start_date,
                'end_date': end_date,
                'total_no_tax': total_no_tax,
                'total_tax': total_tax,
                'total_with_tax': total_with_tax
            }
            report_template_name = 'reports/number_services.html'
        elif report == "rating":
            orders = Order.objects.filter(date_added__gte=start_date, date_added__lte=end_date)

            context = {
                'headers': (
                    'Establecimiento',
                    '# Orden',
                    'Fecha', 
                    'Calificación',
                    'Observación',
                    'Nombre de usuario',
                    'Correo',
                    'Teléfono'
                ),
                'orders': orders
            }
            report_template_name = 'reports/ratings.html'
        elif report == "sales":
            city = City.objects.get(pk=request.POST['city'])
            store = Store.objects.get(pk=request.POST['store'])
            orders = Order.objects.filter(
                related_items__product__store=store,
                date_added__gte=start_date, 
                date_added__lte=end_date,
                status='DE'
            )
             
            context = {
                'headers': (
                    'Establecimiento',
                    '# Orden', 
                    'Fecha', 
                    'Estado',
                    'Precio total',
                    'Valor Domicilio'
                ),
                'orders': orders,
                'store': store,
                'start_date':start_date,
                'end_date': end_date
            }
            report_template_name = 'reports/sales.html'
        elif report == "requests":
            city = City.objects.get(pk=request.POST['city'])
            store = Store.objects.get(pk=request.POST['store'])
            orders = Order.objects.filter(
                related_items__product__store=store,
                date_added__gte=start_date, 
                date_added__lte=end_date,
            )

            context = {
                'headers': (
                    'Establecimiento',
                    '# Orden', 
                    'Fecha', 
                    'Estado',
                    'Precio total',
                    'Nombre usuario',
                    'Correo'
                ),
                'orders': orders,
                'store': store,
                'start_date':start_date,
                'end_date': end_date
            }
            report_template_name = 'reports/requests.html'
        response = HttpResponse(content_type='application/pdf')
        response['Content-Disposition'] = 'attachment; filename="reporte.pdf"'
        result = generate_pdf(report_template_name, file_object=response, context=context)
        return response
    
    def post(self, request, *args, **kwargs):
        report = request.POST['report']
        start_date = request.POST['start']
        end_date = request.POST['end']
        return self.generate_pdf_report(request, report, start_date, end_date)


class RegisteredProducts(TemplateView):
    """
    """

    template_name = 'reports/products.html'


class NumberServices(TemplateView):
    """
    """

    template_name = 'reports/services.html'


class Rating(TemplateView):
    """
    """

    template_name = 'reports/system_rating.html'


class Sales(TemplateView):
    """
    """

    template_name = 'reports/system_sales.html'


class Requests(TemplateView):
    """
    """

    template_name = 'reports/system_requests.html'

merquemos/sales/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from datetime import datetime
from django.http import JsonResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt

from rest_framework import generics
from rest_framework import status
from rest_framework.response import Response

from fcm_django.models import FCMDevice

from api.helpers import get_api_user
from users.models import Address
from .models import Order, Item, DeliveryOrder
from .serializers import (
    OrderSerializer, OrderItemSerializer,
    ItemSerializer, OrderHistorySerializer,
    RatingSerializer, OrderDetailSerializer
)


class CurrentOrderDetail(generics.ListAPIView):
    """Obtiene la información de la orden actual del usuario, obtenida con base en el token del usuario.
    Los estados de orden son los siguientes:
        ('PE', 'Pendiente'),
        ('AC', 'Recibida'),
        ('SH', 'Enviada'),
        ('CA', 'Cancelada'),
        ('DE', 'Entregada')
    Si el parámetro 'base_order' está presente, se creará una orden nueva con base a la orden con la llave primaria
    correspondiente al valor de 'base_order'. En éste último escenario, solo se crearán items cuando cada producto tenga
    stock disponible.
    """

    serializer_class = OrderSerializer

    def get(self, request, format=None):
        user = get_api_user(request)
        if request.GET.get('base_order', None):
            base_order = Order.objects.get(pk=request.GET['base_order'])
            Order.objects.filter(user=user, status='PE').delete()
            order = Order(
                user=user
            )
            order.save()
            for item in base_order.get_items():
                if item.product.is_active:
                    new_item = Item(
                        product=item.product,
                        order=order,
                        quantity=item.quantity
                    )
                    new_item.save()
        else:
            if Order.objects.filter(user=user, status='PE').exists():
                order = Order.objects.filter(user=user, status='PE').last()
            else:
                if Order.objects.filter(user=user, status='AC').exists():
                    order = Order.objects.filter(user=user, status='AC').last()
                elif Order.objects.filter(user=user, status='SH').exists():
                    order = Order.objects.filter(user=user, status='SH').last()
                else:
                    order = Order(
                        user=user
                    )
                    order.save()
        serializer = OrderSerializer(order, many=False)
        return Response(serializer.data)

class CurrentOrderItems(generics.ListAPIView):
    """Obtiene los items de la orden actual, obtenida con base en el token del usuario.
    """

    serializer_class = OrderItemSerializer

    def get(self, request, format=None):
        if Order.objects.filter(user=request.auth.user, status='PE').exists():
            order = Order.objects.get(user=request.auth.user, status='PE')
        elif Order.objects.filter(user=request.auth.user, status='AC').exists():
            order = Order.objects.get(user=request.auth.user, status='AC')
        else:
            return Response(
                {'detail': 'El usuario no tiene compras activas'},
                status=status.HTTP_404_NOT_FOUND
            )
        serializer = OrderItemSerializer(order, many=False)
        return Response(serializer.data)

class OrderItems(generics.ListAPIView):
    """Obtiene los items de la orden actual, obtenida con base en el token del usuario.
    """

    serializer_class = OrderItemSerializer

    def get(self, request, pk, format=None):
        order = Order.objects.get(pk=pk)
        serializer = OrderItemSerializer(order, many=False)
        return Response(serializer.data)

class OrderList(generics.ListAPIView):
    """Obtiene las ordenes de un usuario, obtenido con base en el token de autenticación entregado.
    """

    serializer_class = OrderSerializer

    def get(self, request, format=None):
        orders = Order.objects.filter(user=request.auth.user).exclude(status='PE').order_by('-pk')
        serializer = OrderHistorySerializer(orders, many=True, context={"request": request})
        return Response(serializer.data)

class OrderDetail(generics.RetrieveDestroyAPIView):
    """Edita (HTTP UPDATE) o elimina (DELETE) la orden asociada al
    id entregado en la URL
    """

    serializer_class = OrderDetailSerializer
    queryset = Order.objects.all()

class ItemCreate(generics.CreateAPIView):
    """Crea un nuevo item para la orden actual, la cual se valida a partir del usuario relacinado al Token
    de autenticación enviado.
    """

    serializer_class = ItemSerializer

    def perform_create(self, serializer):
        user = get_api_user(self.request)
        serializer.save(order=user.get_current_order())

class ItemDetail(generics.RetrieveUpdateDestroyAPIView):
    """Edita (HTTP UPDATE) o elimina (DELETE) el item asociado al
    id entregado en la URL
    """

    queryset = Item.objects.all()
    serializer_class = ItemSerializer

class RatingCreate(generics.CreateAPIView):
    """Crea un nuevo registro de calificación para una orden
    """

    serializer_class = RatingSerializer

    def perform_create(self, serializer):
        serializer.save(user=get_api_user(self.request))

@csrf_exempt
def checkout(request):
    order = Order.objects.get(pk=request.POST['order_id'])
    if request.POST['delivery_option'] == DeliveryOrder.POINT:
        order.delivery_price = 0
    else:
        order.delivery_price = order.get_delivery_price()
    order.status = 'AC'
    if request.POST.get('comments', False):
        order.comments = request.POST['comments']
    order.save()

    address = Address.objects.get(pk=request.POST['address_id'])

    payment_method = request.POST['payment_method']
    delivery_option = request.POST['delivery_option']
    delivery_time = request.POST['delivery_time']
    if delivery_time == '':
        delivery_time = datetime.now()
    delivery_order = DeliveryOrder(
        order=order,
        address=address,
        payment_method=payment_method,
        delivery_option=delivery_option,
        delivery_time=delivery_time,
        paid_amount=request.POST.get('total_price', 0)
    )
    delivery_order.save()

    devices = FCMDevice.objects.filter(user=order.user)

    devices.send_message(
        title="Orden aceptada",
        body="Hemos recibido tu orden",
        icon="",
        data={
            "order_id": order.pk,
            "order_status": order.status
        }
    )
    return JsonResponse(
        {
            'detail': 'Compra aceptada satisfactoriamente'
        },
        status=200
    )

@csrf_exempt
def order_cancellation(request):
    order = Order.objects.get(pk=request.POST['order_id'])
    order.status = 'CA'
    order.save()

    return JsonResponse(
        {
            'detail': 'Compra cancelada satisfactoriamente'
        },
        status=200
    )

merquemos/reports/templates/reports/no_attendance.html
<style>
    @page {
        size: letter landscape;
        margin: 2cm;
    }
    table {
        width: 100%;
        text-align: center;
    }
    table, th, td {
        border: 1px solid #161616;
    }
    td {
        padding: 3px;
    }
</style>
<h2>Reporte de inasistencias</h2>
<table>
    <th>
        <tr>
            {% for h in headers %}
                <td>
                    <strong>{{h}}</strong>
                </td>
            {% endfor %}
        </tr>
    </th>
    <tbody>
        {% for r in route_records %}
            <tr>
                <td>{{r.date}}</td>
                <td>{{r.student.get_full_name}}</td>
                <td>{{r.route}}</td>
                <td>{{r.comments}}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>

merquemos/reports/templates/reports/number_services.html
{% load humanize %}

<style>
    @page {
        size: letter landscape;
        margin: 2cm;
    }
    table {
        width: 100%;
        text-align: center;
    }
    table, th, td {
        border: 1px solid #161616;
    }
    td {
        padding: 3px;
    }
</style>
<h1>N&uacute;mero de servicios prestados por {{store.name}}</h1>
<h5>Fechas: Desde {{start_date}} hasta {{end_date}}</h5>

<h2>N&Uacute;MERO DE SERVICIOS: {{count}}</h2>
<h4>Precio total sin IVA: ${{total_no_tax|intcomma}}</h4>
<h4>Precio IVA: ${{total_tax|intcomma}}</h4>
<h4>Precio Total IVA Incluido: ${{total_with_tax|intcomma}}</h4>

merquemos/reports/templates/reports/products.html
{% load static %}

<!doctype html>
<html lang="es">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <style>
            span.input-group-addon {
                display: block;
                margin: 0px 25px;
                font-size: 1.3em;
            }
        </style>

        <title>Reportes Tu mercado</title>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">
                <img src="{% static 'assets/images/logo_footer.png' %}"  class="d-inline-block align-top" alt="">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link" href="/admin">Regresar al administrador <span class="sr-only">(current)</span></a>
                    </li>
                </ul>
            </div>
        </nav>
        <div class="container mt-4">
            <div class="row">
                <div class="col-12">
                    <h5>Reporte de  productos realizados a través de la plataforma</h5>
                    <br>
                    <form method="POST" action="/admin/reports/">
                        {% csrf_token %}
                            <input type="hidden" name="report" value="register_products" />
                                
                            <h6>Fechas</h6>
                            <div class="input-daterange input-group" >
                                <input type="date" class="input-sm form-control" name="start" />
                                <span class="input-group-addon">hasta</span>
                                <input type="date" class="input-sm form-control" name="end" />
                            </div>
                            <br>
                            <button class="btn-secondary mt-4" type="submit">Generar</a>
                    </form>

                </div>
            </div>
        </div>

        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    </body>
</html>

merquemos/reports/templates/reports/products_registered.html
<style>
    @page {
        size: letter landscape;
        margin: 2cm;
    }
    table {
        width: 100%;
        text-align: center;
    }
    table, th, td {
        border: 1px solid #161616;
    }
    td {
        padding: 3px;
    }
</style>
<h2>Reporte de productos realizados a través de la plataforma </h2>
<h5>Fechas: Desde {{start_date}} hasta {{end_date}}</h5>
<table>
    <th>
        <tr>
            {% for h in headers %}
                <td>
                    <strong>{{h}}</strong>
                </td>
            {% endfor %}
        </tr>
    </th>
    <tbody>
        {% for p in products %}
            <tr>
                <td>{{p.name}}</td>
                <td>{{p.description}}</td>
                <td>${{p.price}}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>

merquemos/reports/templates/reports/ratings.html
<style>
        @page {
            size: letter landscape;
            margin: 2cm;
        }
        table {
            width: 100%;
            text-align: center;
        }
        table, th, td {
            border: 1px solid #161616;
        }
        td {
            padding: 3px;
        }
    </style>
    <h2>Reporte de calificaciones de la plataforma </h2>
    <h5>Fechas: Desde {{start_date}} hasta {{end_date}}</h5>
    <table>
        <th>
            <tr>
                {% for h in headers %}
                    <td>
                        <strong>{{h}}</strong>
                    </td>
                {% endfor %}
            </tr>
        </th>
        <tbody>
            {% for o in orders %}
                <tr>
                    <td>{{o.get_store_name}}</td>
                    <td>{{o.id}}</td>
                    <td>{{o.rating.date_added|default:"Sin Fecha"}}</td>
                    <td>{{o.get_rating}}</td>
                    <td>{{o.get_rating_comments}}</td>
                    <td>{{o.user.username}}</td>
                    <td>{{o.user.email}}</td>
                    <td>{{o.user.phone_number|default:"Sin teléfono"}}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

merquemos/reports/templates/reports/report_list.html
{% load i18n %}

<ul>
    <li class="contrast">
        <a href="#" title="Reportes">Reportes</a>
    </li>
    <li>
        <a href="{% url 'reports:products' %}" target="_blank">
            Productos realizados
        </a>
    </li>
    <li>
        <a href="{% url 'reports:services' %}" target="_blank">
            Número de servicios por establecimiento
        </a>
    </li>
    <li>
        <a href="{% url 'reports:rating' %}" target="_blank">
            Calificaciones de la plataforma
        </a>
    </li>
    <li>
        <a href="{% url 'reports:sales' %}" target="_blank">
            Ventas realizadas
        </a>
    </li>
    <li>
        <a href="{% url 'reports:requests' %}" target="_blank">
            Solicitudes realizadas
        </a>
    </li>
</ul>

merquemos/reports/templates/reports/requests.html
{% load humanize %}

<style>
    @page {
        size: letter landscape;
        margin: 2cm;
    }
    table {
        width: 100%;
        text-align: center;
    }
    table, th, td {
        border: 1px solid #161616;
    }
    td {
        padding: 3px;
    }
</style>
<h2>Reporte de solicitudes de la plataforma de la tienda  <strong>{{store}}</strong> </h2>
<h5>Fechas: Desde {{start_date}} hasta {{end_date}}</h5>
<table>
    <th>
        <tr>
            {% for h in headers %}
                <td>
                    <strong>{{h}}</strong>
                </td>
            {% endfor %}
        </tr>
    </th>
    <tbody>
        {% for o in orders %}
            <tr>
                <td>{{o.get_store_name}}</td>
                <td>{{o.id}}</td>
                <td>{{o.date_added|default:"Sin Fecha"}}</td>
                <td>{{o.get_status_display}}</td>
                <td>${{o.get_total_without_delivery|intcomma|default:"Sin precio"}}</td>
                <td>{{o.user.username}}</td>
                <td>{{o.user.email}}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>

merquemos/reports/templates/reports/sales.html
{% load humanize %}

<style>
    @page {
        size: letter landscape;
        margin: 2cm;
    }
    table {
        width: 100%;
        text-align: center;
    }
    table, th, td {
        border: 1px solid #161616;
    }
    td {
        padding: 3px;
    }
</style>
<h2>Reporte de ventas de la plataforma de la tienda {{store}}</h2>
<h5>Fechas: Desde {{start_date}} hasta {{end_date}}</h5>
<table>
    <th>
        <tr>
            {% for h in headers %}
                <td>
                    <strong>{{h}}</strong>
                </td>
            {% endfor %}
        </tr>
    </th>
    <tbody>
        {% for o in orders %}
            <tr>
                <td>{{o.get_store_name}}</td>
                <td>{{o.id}}</td>
                <td>{{o.date_added|default:"Sin Fecha"}}</td>
                <td>{{o.get_status_display}}</td>
                <td>${{o.get_total_without_delivery|intcomma|default:"Sin precio"}}</td>
                <td>${{o.get_delivery_price|intcomma|default:"Sin domicilio"}}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>

merquemos/reports/templates/reports/system_rating.html
{% load static %}

<!doctype html>
<html lang="es">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <style>
            span.input-group-addon {
                display: block;
                margin: 0px 25px;
                font-size: 1.3em;
            }
        </style>

        <title>Reportes Tu mercado</title>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">
                <img src="{% static 'assets/images/logo_footer.png' %}"  class="d-inline-block align-top" alt="">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link" href="/admin">Regresar al administrador <span class="sr-only">(current)</span></a>
                    </li>
                </ul>
            </div>
        </nav>
        <div class="container mt-4">
            <div class="row">
                <div class="col-12">
                    <h5>Reporte de calificaciones de la plataforma</h5>
                    <br>
                    <form method="POST" action="/admin/reports/">
                        {% csrf_token %}
                            <input type="hidden" name="report" value="rating" />
                                
                            <h6>Fechas</h6>
                            <div class="input-daterange input-group" >
                                <input type="date" class="input-sm form-control" name="start" />
                                <span class="input-group-addon">hasta</span>
                                <input type="date" class="input-sm form-control" name="end" />
                            </div>
                            <br>
                            <button class="btn-secondary mt-4" type="submit">Generar</a>
                    </form>

                </div>
            </div>
        </div>

        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    </body>
</html>