merquemos/api/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import (
    password_reset, password_reset_done,
    password_reset_confirm, password_reset_complete
)
from allauth.account.views import ConfirmEmailView

from users.views import UserDetailsView

urlpatterns = [
    url(r'^docs/', include('rest_framework_docs.urls')),
    url(r'^auth/user/$', UserDetailsView.as_view()),
    url(r'^auth/', include('rest_auth.urls')),
    url(r'^manager/', include('manager.urls')),
    url(r'^stock/', include('stock.urls')),
    url(r'^sales/', include('sales.urls', namespace='sales')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^account-confirm-email/(?P<key>[-:\w]+)/$', ConfirmEmailView.as_view(), name='account_confirm_email'),
    url(
        regex=r'^contrib/password_reset/$',
        view=password_reset,
        name='password_reset'
    ),
    url(
        regex=r'^contrib/password_reset/done/$',
        view=password_reset_done,
        name='password_reset_done'
    ),
    url(
        regex=r'^contrib/reset/(?P<uidb64>[0-9A-Za-z_\-]+)'
              r'/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        view=password_reset_confirm,
        name='password_reset_confirm'
    ),
    url(
        regex=r'^contrib/reset/done/$',
        view=password_reset_complete,
        name='password_reset_complete'
    ),
]

merquemos/merquemos/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from reports.views import ReportView 

urlpatterns = [
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    url(r'^admin/', admin.site.urls),
    url(r'^admin/reports/$', ReportView.as_view(), name="admin-reports"),
    url(r'^', include('webclient.urls', namespace='webclient')),
    url(r'^auth/', include('rest_auth.urls')),
    url(r'^reports/', include('reports.urls', namespace='reports')),
    url(r'^auth/registration/', include('rest_auth.registration.urls')),
    url(r'^api/', include('api.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'webclient.views.custom_404'

admin.site.site_header = 'Administrador Mequemos'
admin.site.site_title = 'Administrador Mequemos'

merquemos/rest_framework/urls.py
"""
Login and logout views for the browsable API.

Add these to your root URLconf if you're using the browsable API and
your API requires authentication:

    urlpatterns = [
        ...
        url(r'^auth/', include('rest_framework.urls', namespace='rest_framework'))
    ]

In Django versions older than 1.9, the urls must be namespaced as 'rest_framework',
and you should make sure your authentication settings include `SessionAuthentication`.
"""
from __future__ import unicode_literals

from django.conf.urls import url
from django.contrib.auth import views

template_name = {'template_name': 'rest_framework/login.html'}

app_name = 'rest_framework'
urlpatterns = [
    url(r'^login/$', views.login, template_name, name='login'),
    url(r'^logout/$', views.logout, template_name, name='logout'),
]

merquemos/webclient/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from .views import (
    HomePageView, StoreView, ProductView, 
    AuthView, PrivacyPolicyView, TermsView, FAQView,
    SearchView, CheckoutView, ProfileView, CategoryView,
    SubCategoryView, ExportOrder
)

urlpatterns = [
    url(r'^$', HomePageView.as_view(), name="home"),
    url(r'^login/$', AuthView.as_view(), name="login"),
    url(r'^faq/$', FAQView.as_view(), name="faq"),
    url(r'^signup/$', AuthView.as_view(), name="signup"),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name="logout"),
    url(r'^search/$', SearchView.as_view(), name='search'),
    url(r'^checkout/$', CheckoutView.as_view(), name='checkout'),
    url(r'^profile/$', ProfileView.as_view(), name='profile'),
    url(r'^stores/(?P<city>[\w-]+)/(?P<slug>[\w-]+)/$', StoreView.as_view(), name='store'),
    url(r'^stores/(?P<store_city>[\w-]+)/(?P<store_slug>[\w-]+)/products/(?P<slug>[\w-]+)/$', CategoryView.as_view(), name='category'),
    url(r'^stores/(?P<store_city>[\w-]+)/(?P<store_slug>[\w-]+)/products/(?P<category_parent_slug>[\w-]+)/(?P<slug>[\w-]+)/subcategory/$', SubCategoryView.as_view(), name='subcategory'),
    url(r'^stores/(?P<store_city>[\w-]+)/(?P<store_slug>[\w-]+)/products/(?P<category_slug>[\w-]+)/(?P<slug>[\w-]+)/$', ProductView.as_view(), name='product'),
    url(r'^policies/terms/$', TermsView.as_view(), name="terms"),
    url(r'^policies/privacy/$', PrivacyPolicyView.as_view(), name="privacy-policy"),
    url(r'^export/(?P<pk>[0-9]+)/$', ExportOrder.as_view(), name="export"),
]

merquemos/manager/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.core.exceptions import ValidationError
from django.db import models
from django.utils.text import slugify


class AppPolicy(models.Model):
    """Stores application policies.
    """

    privacy_policy = models.TextField(
        null=True,
        blank=True
    )
    terms_and_conditions = models.TextField(
        null=True,
        blank=True
    )
    
    class Meta:
        verbose_name = 'Poliza de usuario'
        verbose_name_plural = 'Polizas de usuario'
        
    def __unicode__(self):
        return 'Registro de %s' % str(self._meta.verbose_name)

    def clean(self):
        # Don't allow to save new objects if there is a created record.
        if self.__class__.objects.all().count() > 0:
            raise ValidationError('An %s record is already created' % self._meta.verbose_name)
        return True


class FAQCategory(models.Model):
    """Stores Frequently Asked Quetions categories
    """

    name = models.CharField(
        max_length=30,
        unique=True
    )

    class Meta:
        verbose_name = 'Categoría de FAQ'
        verbose_name_plural = 'Categorías de FAQ'

    def __unicode__(self):
        return self.name


class FAQItem(models.Model):
    """Stores FAQ questions per category (FAQCategory)
    """

    category = models.ForeignKey(FAQCategory)
    question = models.TextField(unique=True)
    answer = models.TextField(unique=True)

    class Meta:
        verbose_name = 'Item de FAQ'
        verbose_name_plural = 'Items de FAQ'

    def __unicode__(self):
        return self.question


class State(models.Model):
    """Stores country states
    """

    name = models.CharField(max_length=255)

    class Meta:
        verbose_name = 'Region'
        verbose_name_plural = 'Regiones'

    def __unicode__(self):
        return self.name


class City(models.Model):
    """Stores country cities, referenced by state (State). e.g: Pereira (City), Risaralda (State)
    """

    state = models.ForeignKey(State, related_name="related_cities")
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True, null=True, blank=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Ciudad'
        verbose_name_plural = 'Ciudades'

    def __unicode__(self):
        return self.name
    
    def save(self, *args, **kwargs):
        name = self.state.name + "-" + self.name
        self.slug = slugify(name)
        super(City, self).save(*args, **kwargs)


class ContactMessage(models.Model):
    """Stores contact messages sent from contact form
    """

    title = models.CharField(max_length=255)
    content = models.TextField()

    class Meta:
        verbose_name = 'Mensaje de contacto'
        verbose_name_plural = 'Mensajes de contacto'

    def __unicode__(self):
        return self.title


class Bank(models.Model):

    name = models.CharField(
        'Nombre',
        max_length=255
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Banco'

merquemos/webclient/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

merquemos/webclient/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.http import Http404
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from easy_pdf.views import PDFTemplateView

from manager.models import City, AppPolicy, FAQCategory
from sales.models import Order
from stock.models import Store, Product, Category
from users.models import User


class AuthView(TemplateView):
    template_name = 'auth/auth.html'

    def post(self, request, *args, **kwargs):
        redirect_url = 'webclient:login'

        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            redirect_url = 'webclient:home'
        else:
            messages.add_message(request, messages.WARNING, 'Datos inválidos, reintenta nuevamente.')
        return redirect(redirect_url)


class HomePageView(TemplateView):
    template_name = 'home/store_select.html'

    def post(self, request):
        city = City.objects.get(pk=request.POST['city'])
        request.session['city'] = city.pk
        request.session['city__name'] = city.name
        request.session['state__name'] = city.state.name
        return self.get(request)
    
    def get(self, request, format=None):
        if request.GET.get('change_location', None):
            try:
                del request.session['store']
            except KeyError:
                pass
            if request.user.is_authenticated():
                if request.user.get_current_order():
                    order = request.user.get_current_order()
                    order.delete()
        else:
            user = request.user
            if request.user.is_authenticated():
                if Order.objects.filter(user=user, status='PE').exists():
                    order = Order.objects.filter(user=user, status='PE').last()
                else:
                    if Order.objects.filter(user=user, status='AC').exists():
                        order = Order.objects.filter(user=user, status='AC').last()
                    elif Order.objects.filter(user=user, status='SH').exists():
                        order = Order.objects.filter(user=user, status='SH').last()
                    else:
                        order = Order.objects.create(user=user, status='PE')
                if request.session.get('city', False):
                    city = City.objects.get(pk=request.session['city'])
                    if request.session.get('store', False):
                        store = Store.objects.get(pk=request.session['store'])
                        return redirect('/stores/{}/{}/'.format(city.slug, store.slug))
                    elif order.get_item_quantity() > 0:
                        store = order.related_items.last().product.store.slug
                        return redirect('/stores/{}/{}/'.format(city.slug, store))
        return super(HomePageView, self).get(request)

    def get_context_data(self, **kwargs):
        request = self.request
        context = super(HomePageView, self).get_context_data(**kwargs)
        if request.session.get('city', False):
            city = City.objects.get(pk=request.session['city'])
            context['stores'] = Store.objects.filter(city=city)
            context['city'] = city
        return context


class StoreView(DetailView):
    model = Store
    template_name = 'home/store_detail.html'

    def get(self, request, city, slug):
        request.session['store'] = self.get_object().pk
        if request.user.is_authenticated():
            user = request.user
            order = None
            if Order.objects.filter(user=user, status='PE').exists():
                order = Order.objects.filter(user=user, status='PE').last()
            else:
                if Order.objects.filter(user=user, status='AC').exists():
                    order = Order.objects.filter(user=user, status='AC').last()
                elif Order.objects.filter(user=user, status='SH').exists():
                    order = Order.objects.filter(user=user, status='SH').last()
            if not order:
                pass
            else:
                if order.get_item_quantity() > 0:
                    store = order.related_items.last().product.store.pk
                    if not store == self.get_object().pk:
                        order = request.user.get_current_order()
                        order.delete()

        return super(StoreView, self).get(request)

    def get_object(self, queryset=None):
        try:
            city = City.objects.get(slug=self.kwargs.get('city')) 
        except City.DoesNotExist:
            raise Http404("Ups, tienda no encontrada")
        query = self.get_queryset().filter(city=city)
        return super(DetailView, self).get_object(queryset) 


class ProductView(DetailView):
    model = Product
    template_name = 'product/product_detail.html'

    def get_object(self, queryset=None):
        store = Store.objects.get(slug=self.kwargs.get('store_slug')) 
        query = self.get_queryset().filter(store=store)
        return super(DetailView, self).get_object(queryset) 


class CategoryView(DetailView):
    model = Product
    template_name = 'home/category_detail.html'

    def get_object(self, queryset=None):
        category = Category.objects.get(slug=self.kwargs.get('slug')) 
        return category

    def get_context_data(self, **kwargs):
        context = super(CategoryView, self).get_context_data(**kwargs)
        store_id = self.request.session.get('store', None)
        store = Store.objects.get(pk=store_id)
        context['store'] = store
        return context


class SubCategoryView(ListView):
    model = Product
    template_name = 'home/subcategory_detail.html'
    context_object_name = 'products'
    paginate_by = 18

    def get_queryset(self):
        products = Product.objects.filter(
            store__slug=self.kwargs.get('store_slug'),
            category__slug=self.kwargs.get('slug')
        ).order_by('pk')
        return products

    def get_context_data(self, **kwargs):
        context = super(SubCategoryView, self).get_context_data(**kwargs)
        store_id = self.request.session.get('store', None)
        store = Store.objects.get(pk=store_id)
        category = Category.objects.get(slug=self.kwargs.get('slug'))
        context['store'] = store
        context['category'] = category
        return context


class SearchView(ListView):
    template_name = 'home/search_result.html'

    def get_queryset(self):
        store_id = self.request.session.get('store', None)
        store = Store.objects.get(pk=store_id)
        q = Product.objects.filter(
            name__icontains=self.request.GET.get('q', ''),
            store=store,
            is_active=True
        )
        if self.request.GET.get('category', None):
            q = q.filter(category__parent__pk=self.request.GET['category'])
        return q


class CheckoutView(TemplateView):
    template_name = 'orders/checkout.html'

    def get_context_data(self, **kwargs):
        context = super(CheckoutView, self).get_context_data(**kwargs)
        order = self.request.user.get_current_order()
        try:
            store = order.related_items.first().product.store
        except:
            store = "Sin tienda Asociada"
        context['order'] = order
        context['store'] = store
        return context


class ProfileView(TemplateView):
    template_name = 'user/profile.html'


class PrivacyPolicyView(TemplateView):
    template_name = 'home/policy_detail.html'

    def get_context_data(self, **kwargs):
        policies = AppPolicy.objects.all().last()
        context = super(PrivacyPolicyView, self).get_context_data(**kwargs)
        context['name'] = 'Política de privacidad y tratamiento de datos'
        context['content'] = policies.privacy_policy
        return context


class TermsView(TemplateView):
    template_name = 'home/policy_detail.html'

    def get_context_data(self, **kwargs):
        policies = AppPolicy.objects.all().last()
        context = super(TermsView, self).get_context_data(**kwargs)
        context['name'] = 'Terminos y condiciones'
        context['content'] = policies.terms_and_conditions
        return context


class FAQView(TemplateView):
    template_name = 'home/faq.html'

    def get_context_data(self, **kwargs):
        categories = FAQCategory.objects.all()
        context = super(FAQView, self).get_context_data(**kwargs)
        context['categories'] = categories
        return context


def custom_404(request):
    return render(
        request,
        'webclient/404.html',
        status=None
    )


class ExportOrder(PDFTemplateView):

    template_name = 'admin/order_resume.html'

    def get_context_data(self, **kwargs):
        order = Order.objects.get(pk=self.kwargs.get('pk'))
        return super(ExportOrder, self).get_context_data(
            pagesize='Letter',
            title='Factura Tu mercado',
            order=order,
            **kwargs
        )

merquemos/webclient/templates/home/category_detail.html
{% extends 'webclient/base.html' %}
{% load static %}
{% load webclientextras %}
{% load humanize %}

{% block content %}
<div id="primary" class="content-area">
    <main id="main" class="site-main"> 
        <br>
        {% for category in object.related_categories.all %}
            {% get_5_filtered_products store category as filtered_products %} 
            {% if filtered_products.count > 0 %}
                <section class="products-carousel-tabs animate-in-view fadeIn animated" data-animation="fadeIn">
                    <h2 class="sr-only">Categorias</h2>
                    <ul class="nav nav-inline text-xs-left">
                        <li class="nav-item">
                            <a class="nav-link active">{{category.name}}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" href="/stores/{{store.city.slug}}/{{store.slug}}/products/{{category.parent.slug}}/{{category.slug}}/subcategory/">Ver +</a>
                        </li>         
                    </ul>
                </section><!-- /.products-carousel-tabs -->
                <section class="products-6-1 animate-in-view fadeIn animated" data-animation="fadeIn">
                    <div class="container">
                        <div class="tab-content">
                            <div role="tabpanel" class="tab-pane active" id="grid" aria-expanded="true">  
                                <ul class="products columns-6">
                                    {% for product in filtered_products %}
                                        {% include 'product/product_list_detail.html' %}
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                </section>
            {% endif %}
        {% endfor %}
    </main><!-- #main -->
</div><!-- #primary -->
{% endblock %}

merquemos/webclient/templates/home/faq.html
{% extends 'webclient/base.html' %}
{% load static %}
{% block content%}
<div id="primary" class="content-area">
    <main id="main" class="site-main">
    <br>
        <h2 style="text-align:center;">Preguntas Frecuentes</h2>
        <br>
        {% for c in categories %}
        
            <h4 style="text-align:center;"><strong>{{c.name}}</strong></h4>
            <br>
            {% for i in c.faqitem_set.all %}
                <strong><p>{{i.question}}</p></strong>
                <p>{{i.answer}}</p>
                <br>
            {% endfor %}
        {% endfor %}
        <br> <br> <br>
    </main>
</div>
{% endblock %}

merquemos/webclient/templates/home/policy_detail.html
{% extends 'webclient/base.html' %}
{% load static %}

{% block content %}
    <div id="primary" class="content-area">
        <main id="main" class="site-main">
            <div class="container">
                <br>
                <h2 class="center-align">{{name}}</h2>
                <br>
                <p>{{content}}</p>
                <img class="center-align" src="{% static 'assets/images/logo_footer.png' %}">
            </div>
        </main><!-- #main -->
    </div><!-- #primary -->
{% endblock %}

merquemos/webclient/templates/home/search_result.html
{% extends 'webclient/base.html' %}
{% load static %}
{% load humanize %}

{% block content%}
<div id="primary" class="content-area">
    <main id="main" class="site-main">
    <br>
        
        <section class="products-6-1 animate-in-view fadeIn animated" data-animation="fadeIn">
            <div class="container">
                <div class="tab-content">

                    <div role="tabpanel" class="tab-pane active" id="grid" aria-expanded="true">

                        <ul class="products columns-6">
                            {% for product in object_list %}
                                {% include 'product/product_list_detail.html' %}
                            {% empty %}
                                <div class="center-align">
                                    <img width="330px" src="{% static 'assets/images/error.gif' %}" class="center-align">
                                    <h1>Búsqueda vacía</h1>
                                    <p>No se encontraron productos relacionados con "{{request.GET.q}}". Intenta cambiar tus parámetros de búsqueda</p>
                                    <a href="{% url 'webclient:home' %}" class="social-btn btn-primary">
                                        Regresar
                                    </a> 
                                </div> 
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <!-- /.columns-6-1 -->
            </div>
        </section>

    </main><!-- #main -->
</div><!-- #primary -->
{% endblock %}

merquemos/webclient/templates/home/store_detail.html
{% extends 'webclient/base.html' %}
{% load static %}
{% load webclientextras %}
{% load humanize %}

{% block content %}
<div id="primary" class="content-area">
    <main id="main" class="site-main"> 
        <div class="home-v3-slider" >
            <!-- ========================================== SECTION – HERO : END========================================= -->

            <div id="owl-main" class="owl-carousel owl-inner-nav owl-ui-sm">

                <div class="item" style="background-image: url({{object.get_web_cover_url}});">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-8">
                                <div class="caption vertical-center text-left">

                                    <div class="hero-2 fadeInDown-2">
                                        {{object.name}}
                                    </div>

                                    <div class="hero-action-btn fadeInDown-3 {% if object.is_open %}green-bg{% endif %}" style="background-color: rgba(26, 109, 86, 0.81) !important">
                                        <a class="big le-button">
                                            <strong>{% if object.is_open %}
                                                Abierto
                                            {% else %}
                                                Cerrado
                                            {% endif %}
                                            </strong></br>
                                            <strong>Dirección</strong>: {{object.address}}</br>
                                            <strong>Teléfono</strong>: {{object.phone_number}}
                                        </a>
                                    </div>
                                </div><!-- /.caption -->
                            </div><!-- /.col -->
                        </div>
                    </div><!-- /.container -->
                </div><!-- /.item -->

            </div><!-- /.owl-carousel -->

            <!-- ========================================= SECTION – HERO : END ========================================= -->

        </div><!-- /.home-v1-slider -->
        

        {% for category in webclient_context_categories %}
            {% get_5_filtered_products object category as filtered_products %} 
            {% if filtered_products.count > 0 %}
                <section class="products-carousel-tabs animate-in-view fadeIn animated" data-animation="fadeIn">
                    <h2 class="sr-only">Categorias</h2>
                    <ul class="nav nav-inline text-xs-left">
                        <li class="nav-item">
                            <a class="nav-link active">{{category.name}}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" href="/stores/{{object.city.slug}}/{{object.slug}}/products/{{category.slug}}/">Ver +</a>
                        </li>                                    
                    </ul>
                </section><!-- /.products-carousel-tabs -->
                <section class="products-6-1 animate-in-view fadeIn animated" data-animation="fadeIn">
                    <div class="container">
                        <div class="tab-content">
                            <div role="tabpanel" class="tab-pane active" id="grid" aria-expanded="true">  
                                <ul class="products columns-6">
                                    {% for product in filtered_products %}
                                        {% include 'product/product_list_detail.html' %}
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                </section>
            {% endif %}
        {% endfor %}
    </main><!-- #main -->
</div><!-- #primary -->
{% endblock %}

merquemos/webclient/templates/home/store_select.html
{% extends 'webclient/base.html' %}
{% load static %}

{% block content %}
    <div id="primary" class="content-area">
        <main id="main" class="site-main">
            <article class="has-post-thumbnail hentry">
                <header class="entry-header header-with-cover-image" style="background-image: url({% static 'assets/images/products/header-image.png' %});">
                    <div class="caption">
                        <h1 class="entry-title" itemprop="name">Seleccione su ciudad</h1>
                        <br>                                        
                        <a type="button" class="btn btn-secondary" data-toggle="modal" data-target="#citySelectionModal" >
                            <span class="button_icon">
                                <i class="icon-layout"></i>
                            </span> 
                            <span class="button_label">Selecciona la Ciudad</span>
                        </a>
                    </div>
                </header><!-- .entry-header -->

                {% if request.session.city %}
                    <div class="entry-content">
                        <div class="row about-features inner-top-md inner-bottom-sm">
                            <h1 class="entry-title" itemprop="name">{{city.name}}</h1>
                            {% for store in stores %}
                                <div class="col-xs-12 col-md-3">
                                    <figure class="wpb_wrapper vc_figure outer-bottom-xs">
                                        <div class="vc_single_image-wrapper">
                                            <a href="/stores/{{store.city.slug}}/{{store.slug}}">
                                                <img src="{{store.logo.url}}" data-echo="{{store.logo.url}}" class="img-responsive" alt="">
                                            </a>
                                        </div>
                                    </figure>
                                </div><!-- .col -->
                            {% endfor %}
                        </div><!-- .row -->
                    </div><!-- .entry-content -->
                {% endif %}

            </article><!-- #post-## -->
        </main><!-- #main -->
    </div><!-- #primary -->
{% endblock %}

{% block extra_js %}
<script>
    (function($) {
        {% if not request.session.city %}
            $('#citySelectionModal').modal('show');
        {% endif %}
    })(jQuery);
</script>
{% endblock %}

merquemos/webclient/templates/home/subcategory_detail.html
{% extends 'webclient/base.html' %}
{% load static %}
{% load webclientextras %}
{% load humanize %}

{% block content %}
<div id="primary" class="content-area">
    <main id="main" class="site-main"> 
        <br>
        <section class="products-carousel-tabs animate-in-view fadeIn animated" data-animation="fadeIn">
            <h2 class="sr-only">Categorias</h2>
            <ul class="nav nav-inline text-xs-left">
                <li class="nav-item">
                    <a class="nav-link active">{{category.name}}</a>
                </li>                         
            </ul>
        </section><!-- /.products-carousel-tabs -->
        <section class="products-6-1 animate-in-view fadeIn animated" data-animation="fadeIn">
            <div class="container">
                <div class="tab-content">
                    <div role="tabpanel" class="tab-pane active" id="grid" aria-expanded="true">  
                        <ul class="products columns-6">
                            {% for product in products %}
                                {% include 'product/product_list_detail.html' %}
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                {% if is_paginated %}
                <div class="paginated">
                    <ul class="pagination-prod">
                        {% if page_obj.has_previous %}
                            <a href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
                        {% else %}
                            <a class="disabled"><span>&laquo;</span></a>
                        {% endif %}
                        {% for i in paginator.page_range %}
                            {% if page_obj.number == i %}
                                <a class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></a>
                            {% else %}
                                <a href="?page={{ i }}">{{ i }}</a>
                            {% endif %}
                        {% endfor %}
                        {% if page_obj.has_next %}
                            <a href="?page={{ page_obj.next_page_number }}">&raquo;</a>
                        {% else %}
                            <a class="disabled"><span>&raquo;</span></a>
                        {% endif %}
                    </ul>
                </div>
                {% endif %}
            </div>
        </section>
    </main><!-- #main -->
</div><!-- #primary -->
{% endblock %}