merquemos/api/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import (
    password_reset, password_reset_done,
    password_reset_confirm, password_reset_complete
)
from allauth.account.views import ConfirmEmailView

from users.views import UserDetailsView

urlpatterns = [
    url(r'^docs/', include('rest_framework_docs.urls')),
    url(r'^auth/user/$', UserDetailsView.as_view()),
    url(r'^auth/', include('rest_auth.urls')),
    url(r'^manager/', include('manager.urls')),
    url(r'^stock/', include('stock.urls')),
    url(r'^sales/', include('sales.urls', namespace='sales')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^account-confirm-email/(?P<key>[-:\w]+)/$', ConfirmEmailView.as_view(), name='account_confirm_email'),
    url(
        regex=r'^contrib/password_reset/$',
        view=password_reset,
        name='password_reset'
    ),
    url(
        regex=r'^contrib/password_reset/done/$',
        view=password_reset_done,
        name='password_reset_done'
    ),
    url(
        regex=r'^contrib/reset/(?P<uidb64>[0-9A-Za-z_\-]+)'
              r'/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        view=password_reset_confirm,
        name='password_reset_confirm'
    ),
    url(
        regex=r'^contrib/reset/done/$',
        view=password_reset_complete,
        name='password_reset_complete'
    ),
]

merquemos/merquemos/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from reports.views import ReportView 

urlpatterns = [
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    url(r'^admin/', admin.site.urls),
    url(r'^admin/reports/$', ReportView.as_view(), name="admin-reports"),
    url(r'^', include('webclient.urls', namespace='webclient')),
    url(r'^auth/', include('rest_auth.urls')),
    url(r'^reports/', include('reports.urls', namespace='reports')),
    url(r'^auth/registration/', include('rest_auth.registration.urls')),
    url(r'^api/', include('api.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'webclient.views.custom_404'

admin.site.site_header = 'Administrador Mequemos'
admin.site.site_title = 'Administrador Mequemos'

merquemos/rest_framework/urls.py
"""
Login and logout views for the browsable API.

Add these to your root URLconf if you're using the browsable API and
your API requires authentication:

    urlpatterns = [
        ...
        url(r'^auth/', include('rest_framework.urls', namespace='rest_framework'))
    ]

In Django versions older than 1.9, the urls must be namespaced as 'rest_framework',
and you should make sure your authentication settings include `SessionAuthentication`.
"""
from __future__ import unicode_literals

from django.conf.urls import url
from django.contrib.auth import views

template_name = {'template_name': 'rest_framework/login.html'}

app_name = 'rest_framework'
urlpatterns = [
    url(r'^login/$', views.login, template_name, name='login'),
    url(r'^logout/$', views.logout, template_name, name='logout'),
]

merquemos/sales/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import (
    CurrentOrderDetail, ItemCreate, OrderList,
    CurrentOrderItems, ItemDetail, OrderDetail, checkout,
    RatingCreate, order_cancellation, OrderItems
)

urlpatterns = [
    url(r'^current-order/$', CurrentOrderDetail.as_view(), name="current-order"),
    url(r'^current-order/items/$', CurrentOrderItems.as_view(), name="current-order-items"),
    url(r'^orders/$', OrderList.as_view(), name="order-list"),
    url(r'^order/(?P<pk>[0-9]+)/$', OrderDetail.as_view(), name="order-detail"),
    url(r'^order/(?P<pk>[0-9]+)/items/$', OrderItems.as_view(), name="order-items"),
    url(r'^item/$', ItemCreate.as_view(), name="item-create"),
    url(r'^item/(?P<pk>[0-9]+)/$', ItemDetail.as_view(), name="item-detail"),
    url(r'^checkout/$', checkout, name="checkout"),
    url(r'^cancellation/$', order_cancellation, name="cancellation"),
    url(r'^rating/$', RatingCreate.as_view(), name="rating-create"),
]

merquemos/webclient/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from .views import (
    HomePageView, StoreView, ProductView, 
    AuthView, PrivacyPolicyView, TermsView, FAQView,
    SearchView, CheckoutView, ProfileView, CategoryView,
    SubCategoryView, ExportOrder
)

urlpatterns = [
    url(r'^$', HomePageView.as_view(), name="home"),
    url(r'^login/$', AuthView.as_view(), name="login"),
    url(r'^faq/$', FAQView.as_view(), name="faq"),
    url(r'^signup/$', AuthView.as_view(), name="signup"),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name="logout"),
    url(r'^search/$', SearchView.as_view(), name='search'),
    url(r'^checkout/$', CheckoutView.as_view(), name='checkout'),
    url(r'^profile/$', ProfileView.as_view(), name='profile'),
    url(r'^stores/(?P<city>[\w-]+)/(?P<slug>[\w-]+)/$', StoreView.as_view(), name='store'),
    url(r'^stores/(?P<store_city>[\w-]+)/(?P<store_slug>[\w-]+)/products/(?P<slug>[\w-]+)/$', CategoryView.as_view(), name='category'),
    url(r'^stores/(?P<store_city>[\w-]+)/(?P<store_slug>[\w-]+)/products/(?P<category_parent_slug>[\w-]+)/(?P<slug>[\w-]+)/subcategory/$', SubCategoryView.as_view(), name='subcategory'),
    url(r'^stores/(?P<store_city>[\w-]+)/(?P<store_slug>[\w-]+)/products/(?P<category_slug>[\w-]+)/(?P<slug>[\w-]+)/$', ProductView.as_view(), name='product'),
    url(r'^policies/terms/$', TermsView.as_view(), name="terms"),
    url(r'^policies/privacy/$', PrivacyPolicyView.as_view(), name="privacy-policy"),
    url(r'^export/(?P<pk>[0-9]+)/$', ExportOrder.as_view(), name="export"),
]

merquemos/stock/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.core.exceptions import ValidationError
from django.db import models
from django.urls import reverse_lazy
from django.utils.text import slugify

from manager.models import City, Bank


class Store(models.Model):

    AHORROS = 'AH'
    CORRIENTE = 'CO'

    BANK_TYPE = (
        (AHORROS, 'Ahorros'),
        (CORRIENTE, 'Corriente'),
    )

    name = models.CharField('Nombre', max_length=255, unique=True)
    legal_id_number = models.CharField('NIT', max_length=255, unique=True)
    manager = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name='Administrador',
        related_name='related_store',
        blank=True, null=True
    )
    logo = models.ImageField('logo', upload_to="stock/stores/logos/")
    city = models.ForeignKey(City, verbose_name='Ciudad', related_name="related_stores")
    address = models.CharField('Dirección', max_length=255)
    phone_number = models.CharField('Número telefónico', max_length=255)
    app_cover = models.ImageField(
        verbose_name='Imágen para Móvil',
        upload_to="stock/stores/app_covers/",
        null=True,
        blank=True
    )
    web_cover = models.ImageField(
        verbose_name='Imágen para Web',
        upload_to="stock/stores/web_covers/",
        null=True,
        blank=True
    )
    app_hex_code = models.CharField('Código HEX color', max_length=10, null=True, blank=True)
    slug = models.SlugField(unique=True, null=True, blank=True)
    is_active = models.BooleanField('Tienda activa?', default=True)
    bank = models.ForeignKey(
        Bank,
        verbose_name='Banco',
        null=True, blank=True
    )
    bank_type = models.CharField(
        'Tipo de cuenta',
        choices=BANK_TYPE,
        max_length=2,
        null=True,
        blank=True
    )
    bank_number = models.CharField(
        'Numero de cuenta',
        max_length=20,
        null=True, blank=True
    )

    class Meta:
        verbose_name = "Tienda"

    def __str__(self):
        return str(self.name)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Store, self).save(*args, **kwargs)

    def get_delivery_price(self):
        if self.related_parameters.all().count() > 0:
            params = self.related_parameters.all().last()
            return params.delivery_price
        return 0

    @models.permalink
    def get_absolute_url(self):
        return reverse_lazy('webclient:store', args=(self.city.name, self.slug))

    def is_open(self):
        if self.related_hours.all().count() > 0:
            return True
        return True

    def get_web_cover_url(self):
        if self.web_cover:
            return self.web_cover.url
        else:
            return ''


class StoreContact(models.Model):
    store = models.ForeignKey(Store, related_name='related_contacts')
    name = models.CharField(max_length=255)
    phone_number = models.CharField(max_length=15)
    email = models.EmailField()
    occupation = models.CharField(max_length=255)

    class Meta:
        verbose_name = "Contacto"

    def __str__(self):
        return str(self.name)


class StoreHour(models.Model):
    DAY_CHOICES = (
        (1, 'Lunes'),
        (2, 'Martes'),
        (3, 'Miercoles'),
        (4, 'Jueves'),
        (5, 'Viernes'),
        (6, 'Sábado'),
        (7, 'Domingo'),
    )
    store = models.ForeignKey(Store, related_name='related_hours')
    day = models.CharField(max_length=1, choices=DAY_CHOICES)
    open_time = models.TimeField()
    close_time = models.TimeField()

    class Meta:
        verbose_name = "Horario"
        unique_together = ('store', 'day')

    def __str__(self):
        return str(self.day.get_display_name())


class StoreParameter(models.Model):
    store = models.ForeignKey(Store, related_name='related_parameters')
    delivery_price = models.DecimalField('Precio Domicilio', max_digits=10, decimal_places=2, default=0)

    def __unicode__(self):
        return "Parámetro de la tienda"

    class Meta:
        verbose_name = "Parámetro de tienda"
        verbose_name_plural = "Parámetros de tiendas"


class Brand(models.Model):
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        verbose_name = "Marca"

    def __str__(self):
        return str(self.name)


class BrandStore(models.Model):
    brand = models.ForeignKey(Brand)
    store = models.ForeignKey(Store)

    class Meta:
        verbose_name = "Marca por tienda"
        verbose_name_plural = "Marcas por tiendas"

    def __str__(self):
        return str(self.brand)


class Category(models.Model):
    name = models.CharField(max_length=255)
    parent = models.ForeignKey('self', null=True, blank=True, related_name="related_categories")
    slug = models.SlugField(unique=True, null=True, blank=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        verbose_name = "Categoría"
        ordering = ['name', ]

    def __str__(self):
        return str(self.name)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    def get_related_products(self, store=None):
        if self.parent is not None:
            queryset = self.related_products.all()
        else:
            queryset = Product.objects.filter(category__parent=self)
        if store is not None:
            queryset = queryset.filter(store=store)
        return queryset


class Product(models.Model):
    GRAMO = 'GR'
    KILOGRAMO = 'KG'
    MILILITRO = 'ML'
    LITRO = 'LT'
    CENTIMETRO = 'CM'
    METRO = 'MT'

    PUM = (
        (GRAMO, 'Gramo'),
        (KILOGRAMO, 'Kilogramo'),
        (MILILITRO, 'Mililitro'),
        (LITRO, 'Litro'),
        (CENTIMETRO, 'Centimetro'),
        (METRO, 'Metro')
    )

    store = models.ForeignKey(Store)
    brand = models.ForeignKey(BrandStore)
    category = models.ForeignKey(Category, related_name='related_products')
    sku = models.CharField(max_length=255)
    barcode = models.TextField(null=True, blank=True)
    name = models.CharField(max_length=255, unique=True, )
    description = models.TextField()
    image = models.ImageField(upload_to="stock/products/images/", default="logo.png")
    tax_percentage = models.DecimalField(max_digits=10, decimal_places=2)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    size = models.CharField(max_length=255)
    stock_quantity = models.PositiveIntegerField(editable=False, default=0)
    discount_percentage = models.PositiveIntegerField(default=0)
    slug = models.SlugField(unique=True, null=True, blank=True)
    is_active = models.BooleanField(default=True)
    date_added = models.DateField(auto_now_add=True)
    pum_value = models.DecimalField(
        'Precio por unidad de medida',
        decimal_places=2,
        max_digits=10,
        default=0
    )
    pum_type = models.CharField(
        'Unidad de medida',
        max_length=2,
        choices=PUM,
        null=True,
        blank=True
    )

    class Meta:
        verbose_name = "Producto"
        ordering = ['name', ]

    def __str__(self):
        return str(self.name)

    def clean(self):
        if self.category.parent is None:
            raise ValidationError("La categoría seleccionada para el producto no puede ser {}, pues es una categoría principal. Por favor,\
            selecciona una subcategoría".format(self.category.name))

    def save(self, *args, **kwargs):
        name = self.name.replace('.', '')
        self.slug = slugify(name)
        super(Product, self).save(*args, **kwargs)

    def has_discount(self):
        if self.discount_percentage > 0:
            return True
        return False

    def get_discount_value(self):
        return self.discount_percentage * self.price / 100

    def get_tax_value(self):
        return self.tax_percentage * self.price / 100

    def get_price(self):
        if self.has_discount():
            return self.price - self.get_discount_value()
        return self.price

    def get_price_no_tax(self):
        return self.get_price() - self.get_tax_value()

    def get_image_url(self):
        if self.image:
            return self.image.url
        return None


class Inventory(models.Model):
    product = models.ForeignKey(Product)
    quantity = models.PositiveIntegerField()
    date_added = models.DateTimeField(auto_now_add=True, null=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True)

    class Meta:
        verbose_name = "Inventario"

    def __str__(self):
        return str(self.quantity)

    def __init__(self, *args, **kwargs):
        super(Inventory, self).__init__(*args, **kwargs)
        # Save last quantity value
        self.last_quantity = self.quantity

    def save(self, raw=False, *args, **kwargs):
        if raw is False:
            # Increase product stock quantity when Inventory object is saved
            self.last_quantity
            self.product.stock_quantity = self.product.stock_quantity + self.quantity
            self.product.save()
            super(Inventory, self).save(*args, **kwargs)

merquemos/webclient/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

merquemos/webclient/templates/product/product_detail.html
{% extends 'webclient/base.html' %}
{% load static %}
{% load humanize %}

{% block extra_css %}
<style>
body {font-family: Arial, Helvetica, sans-serif;}

#prod-img:hover {
  opacity: 0.7;
  cursor: pointer;
}

/* The Modal (background) */
.modal {
  display: none; /* Hidden by default */
  position: fixed; /* Stay in place */
  z-index: 999; /* Sit on top */
  padding-top: 100px; /* Location of the box */
  left: 0;
  top: 0;
  width: 100%; /* Full width */
  height: 100%; /* Full height */
  overflow: auto; /* Enable scroll if needed */
  background-color: rgb(0,0,0); /* Fallback color */
  background-color: rgba(0,0,0,0.7); /* Black w/ opacity */
}

/* Modal Content (image) */
.modal-content {
  margin: auto;
  display: block;
  width: 80%;
  max-width: 700px;
}

/* Add Animation */
.modal-content, #caption {
  -webkit-animation-name: zoom;
  -webkit-animation-duration: 0.6s;
  animation-name: zoom;
  animation-duration: 0.6s;
}

@-webkit-keyframes zoom {
  from {-webkit-transform:scale(0)}
  to {-webkit-transform:scale(1)}
}

@keyframes zoom {
  from {transform:scale(0)}
  to {transform:scale(1)}
}

/* The Close Button */
#close {
  position: absolute;
  top: 15px;
  right: 35px;
  color: #f1f1f1;
  font-size: 40px;
  font-weight: bold;
  transition: 0.3s;
}

#close:hover,
#close:focus {
  color: #bbb;
  text-decoration: none;
  cursor: pointer;
}

/* 100% Image Width on Smaller Screens */
@media only screen and (max-width: 700px){
  .modal-content {
    width: 100%;
  }
}
</style>

{% endblock %}

{% block content %}
<div id="primary" class="content-area">
  <main id="main" class="site-main">

    <div class="product">

      <div class="single-product-wrapper">
        <div class="product-images-wrapper">
          <div class="images electro-gallery">
            <img src="{{product.get_image_url}}" class="wp-post-image" id="prod-img" alt="">
          </div><!-- .electro-gallery -->
        </div><!-- /.product-images-wrapper -->

        <div class="summary entry-summary">

                    <span class="loop-product-categories">
                        <a rel="tag">{{product.categoy.name}}</a>
                    </span><!-- /.loop-product-categories -->

          <h1 itemprop="name" class="product_title entry-title">{{product.name}}</h1>

          <hr class="single-product-title-divider"/>

          <div itemprop="description">
            <p>{{product.description}}</p>
            <p><strong>Referencia</strong>: {{product.sku}}</p>
            <p><strong>Presentación</strong>: {{product.size}}</p>
            <p><strong>PUM</strong>: ${{product.pum_value}} x {{product.get_pum_type_display}}</p>
          </div><!-- .description -->

          <div itemprop="offers" itemscope itemtype="http://schema.org/Offer">

            <p class="price"><span class="electro-price">
                        <ins><h4 class="amount">&#36;{{product.get_price|intcomma}}</h4></ins> 
                        {% if product.has_discount %}
                        <del><span class="amount">&#36;{{product.price|intcomma}}</span></del></span></p>
            {% endif %}
            <meta itemprop="price" content="{{product.price|intcomma}}"/>
            <meta itemprop="priceCurrency" content="COP"/>
            <link itemprop="availability" href="http://schema.org/InStock"/>

          </div><!-- /itemprop -->

          <form class="variations_form cart" method="POST" id="add_to_cart_form">

            <div class="single_variation_wrap">
              <div class="woocommerce-variation single_variation"></div>
              <div class="woocommerce-variation-add-to-cart variations_button">
                <div class="quantity">
                  <label>Cantidad:</label>
                  <input type="number" name="quantity" value="1" title="Qty"
                         class="input-text qty text quantity_selector" min="1"/>
                </div>
                <button type="submit" class="single_add_to_cart_button button">Agregar al carrito</button>
                <input type="hidden" name="product" value="{{product.pk}}"/>
              </div>
            </div>
          </form>

        </div><!-- .summary -->
      </div><!-- /.single-product-wrapper -->
    </div><!-- /.product -->

  </main><!-- /.site-main -->
</div><!-- /.content-area -->

<!-- The Modal -->
<div id="myModal" class="modal">
  <span id="close">&times;</span>
  <img class="modal-content" id="img01">
</div>
{% endblock %}

{% block extra_js %}
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@8"></script>
<script>
  (function ($) {
    $('#add_to_cart_form').on('submit', function (e) {
      e.preventDefault();
      {% if not request.user.is_authenticated %}
      window.location.replace("{% url 'webclient:login' %}");
      {% endif %}
      var jqxhr = $.post("{% url 'sales:item-create' %}", $(this).serialize(), function (data) {
        Swal.fire({
          title: 'Producto agregado exitosamente',
          text: "El producto se ha agregado al carrito exitosamente. Quieres agregar más productos, o ir al carrito?",
          type: 'success',
          showCancelButton: true,
          confirmButtonColor: '#BB5353',
          cancelButtonColor: '#55ba95',
          confirmButtonText: 'Agregar más productos',
          cancelButtonText: 'Ir al carrito'
        }).then((result) => {
          if (result.value) {
            window.history.go(-1)
          } else {
            location.href = "{% url 'webclient:checkout' %}"
          }
        })
        update_cart();
      });
    });
    $('#close').on('click', function () {
      console.log("Close MODAL")
      modal.style.display = "none";
    })
  })(jQuery);

  var modal = document.getElementById("myModal");
  // Get the image and insert it inside the modal - use its "alt" text as a caption
  var img = document.getElementById("prod-img");
  var modalImg = document.getElementById("img01");
  img.onclick = function(){
    modal.style.display = "block";
    modalImg.src = this.src;
  }

</script>
{% endblock %}

merquemos/webclient/templates/product/product_list_detail.html
{% load humanize %}

<li class="product {% if forloop.first %}first{% endif %} {% if forloop.last %}last{% endif %}">
    <div class="product-outer">
        <div class="product-inner">
            <span class="loop-product-categories">{{product.category}}</span>
            <a href="/stores/{{product.store.city}}/{{product.store.slug}}/products/{{product.category.slug}}/{{product.slug}}/">
                <h3>{{product.name}}</h3>
                <div class="product-thumbnail">
                    <img data-echo="{{product.get_image_url}}" src="{{product.get_image_url}}" alt="{{product.name}}">
                </div>
            </a>

            <div class="price-add-to-cart">
                <a rel="nofollow" href="/stores/{{product.store.city}}/{{product.store.slug}}/products/{{product.category.slug}}/{{product.slug}}/" class="button add_to_cart_button">Agregar al carrito</a>
                <span class="price">
                    <span class="electro-price">
                        <ins><span class="amount">${{product.get_price.normalize|intcomma}}</span></ins>
                        {% if product.has_discount %}
                            <del><span class="amount">${{product.price.normalize|intcomma}}</span></del>
                        {% endif %}
                    </span>
                     <span class="pum-price ">
                        <ins><span class="pum">${{product.pum_value|intcomma}} x {{product.get_pum_type_display}}</span></ins>
                      </span>
                </span>
                
            </div><!-- /.price-add-to-cart -->
        </div><!-- /.product-inner -->
    </div><!-- /.product-outer -->
</li>